// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvOkeQzPLiqMLMKt90Z6_7P8d90BHIJmg',
    appId: '1:275973691872:web:728baf15f656d0d13df385',
    messagingSenderId: '275973691872',
    projectId: 'foodsaver-5f6c7',
    authDomain: 'foodsaver-5f6c7.firebaseapp.com',
    storageBucket: 'foodsaver-5f6c7.appspot.com',
    measurementId: 'G-4RFJ9F7XPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3TQprwNBqRQlnrMCpOghwJmfpD2r_L90',
    appId: '1:275973691872:android:1c2f6937c6c0cb503df385',
    messagingSenderId: '275973691872',
    projectId: 'foodsaver-5f6c7',
    storageBucket: 'foodsaver-5f6c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO-9tAkZcWxb62FMXV48R5QFzw0Rwx-jM',
    appId: '1:275973691872:ios:05fe09a09b8555dc3df385',
    messagingSenderId: '275973691872',
    projectId: 'foodsaver-5f6c7',
    storageBucket: 'foodsaver-5f6c7.appspot.com',
    iosBundleId: 'com.example.foodsaver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO-9tAkZcWxb62FMXV48R5QFzw0Rwx-jM',
    appId: '1:275973691872:ios:804102bc012832493df385',
    messagingSenderId: '275973691872',
    projectId: 'foodsaver-5f6c7',
    storageBucket: 'foodsaver-5f6c7.appspot.com',
    iosBundleId: 'com.example.foodsaver.RunnerTests',
  );
}
